### ISSUE TITLE
UAT Feedback - If Net runway value is negative. Show the following text in the graph

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#534] opened 2020-04-23 05:30 UTC
![image](https://user-images.githubusercontent.com/43877959/80062588-bf817900-8551-11ea-8680-56195776519c.png)

**Comment by HazelColaco19** [comment] 2020-04-29 13:40
1. Design wise the circle is missing an outer darker blue circle 
2. The circle as well is proportionally smaller than the one in design

![image](https://user-images.githubusercontent.com/55691499/80602605-f6252b00-8a4c-11ea-8384-c6f8df3796d3.png)

**Comment by HazelColaco19** [comment] 2020-04-30 06:07
Looks fixed on projection 


![image](https://user-images.githubusercontent.com/55691499/80677563-be62c580-8ad6-11ea-8362-defc1508f516.png)


However for an older projection 43345, the issue is seen as is

**Comment by georgioajency** [comment] 2020-04-30 13:13
2 issues here

1. Positive Net Operating Cashflow
You have mentioned opening

2.  Can you increase the font size? It looks really small on my system
![image](https://user-images.githubusercontent.com/43877959/80714412-87aaa080-8b12-11ea-925f-9c99e7dc624f.png)

**Comment by HazelColaco19** [comment] 2020-05-05 07:37
Looks fixed

![image](https://user-images.githubusercontent.com/55691499/81044133-5a267400-8ed1-11ea-8cdf-79737d3a4bc2.png)

**Closed as completed by HazelColaco19** 2020-05-05 07:37 UTC
Labels: enhancement, UI Change, assign-to-qa, UAT feedback
