### ISSUE TITLE
BUG - Added expense doesn't open exact link. I checked for some and opened blank screen

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#363] opened 2020-04-07 04:29 UTC
Edit Link opens up a blank screen.

This may be similar to that of expenses not getting added to Toppeq in spite of the WhatsApp bot showing it has been added.
One possibility for both unpaid and paid expenses is that the due date entered in the past.
7204 7200 7914 7906 7796 7930

![image](https://user-images.githubusercontent.com/43877959/78629162-dcf8e680-78b3-11ea-9657-e1f7fb1298b4.png)

I also found a case wherein the date was added in the future however the expense was not opening up on Toppeq - 7938 (This was the only case where I have manually added people under notifications)
![image](https://user-images.githubusercontent.com/43877959/78629193-f4d06a80-78b3-11ea-9829-69aa16f9188a.png)

**Comment by dattaprasad-ekavade** [comment] 2020-04-08 05:25
![image](https://user-images.githubusercontent.com/48904574/78747368-e1da9a80-7986-11ea-993a-ce19c97b02d7.png)
All the entries noted above are present in DB. 

`One possibility for both unpaid and paid expenses is that the due date entered in the past.`
This seems like a probable reason but doesn't seem to be the sole cause for the issue as 7938 show the correct date

**Comment by nutank** [comment] 2020-04-09 10:39
@dattaprasad-ekavade please check if you can replicate the issue. without replicating the issue we wont be able to do a fix.

Please put a label of "Could not reproduce" if cannot replicate.

**Comment by dattaprasad-ekavade** [comment] 2020-04-13 09:36
Able to reproduce the issue, Can confirm its because of the due date entered in the past.

**Comment by georgioajency** [comment] 2020-04-13 17:48
@dattaprasad-ekavade @nutank 
Still getting this issue. 
https://ajency-qa.toppeq.com/cashflow/outflow/planned#/db_37236

![image](https://user-images.githubusercontent.com/43877959/79144691-01395380-7ddd-11ea-9ab2-8cfa8cac62ab.png)

**Comment by dattaprasad-ekavade** [comment] 2020-04-15 05:51
Got the URL working fine. 
Note: once clicked on URL, it asks for Login credentials and then redirects to https://ajency-qa.toppeq.com/fund_of_fund instead of the http://ajency-qa.toppeq.com/cashflow/outflow/planned#/db_38937 URL. 

![image](https://user-images.githubusercontent.com/48904574/79302789-f250bf00-7f0a-11ea-9fb0-dc79345717f3.png)

**Comment by georgioajency** [comment] 2020-04-15 06:54
@dattaprasad-ekavade I know about that redirect issue. However, on that day this expense was not loading up. Noticed this before also. When testing some of them don't load at that point in time. However, when checked the next day it shows up.

**Comment by HazelColaco19** [comment] 2020-04-22 12:59
On click of the expense link, it takes the user to login page of toppeq website and upon login it lands you on the  https://ajency-qa.toppeq.com/fund_of_fund instead of the expense URL. 

The flow does not seem right from users perspective. 

However you can close this if it okay with you @georgioajency

**Closed as completed** 2020-04-23 12:01 UTC
Labels: bug, To be handled, Not an issue, whatsapp bot
