### ISSUE TITLE
BUG - Opening Balance not matching for Rent & Lease

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#625] opened 2020-05-08 15:19 UTC
QB
![image](https://user-images.githubusercontent.com/55691499/81420268-5f075400-916d-11ea-9d11-a109845b9eac.png)

Website
![image](https://user-images.githubusercontent.com/55691499/81420305-6c244300-916d-11ea-908a-9f25c9a971b6.png)

**Comment by nutank** [comment] 2020-05-10 19:36
Could be a possible duplicate of #622

**Comment by nutank** [comment] 2020-05-10 19:48
Closing this, tracking the ticket in #629

**Closed as completed by nutank** 2020-05-10 19:48 UTC
Labels: bug
